# Auto Generated Dockerfile

FROM openjdk:8-jre-alpine
LABEL maintainer="dev@ballerina.io"

WORKDIR /home/ballerina
COPY hello_world_service.jar /home/ballerina 

EXPOSE  9090
CMD java -jar hello_world_service.jar
